### ISSUE TITLE
Adding buttons

### ISSUE THREAD

**Issue by sommerper** [valeriosetti/ploopy-nano-kicad#1]
Hi!

This looks interesting!

I was wondering if there is a way to add buttons to this and make a complete trackball unit. I couldn't quite figure that out just by looking at the pcb in kicad.

Thanks!

**Comment by valeriosetti** [comment]
Hi!!

Yes, adding buttons is something I would definitely want to try in the future (actually 3/4 buttons and a knob for scrolling). 

On one hand I didn't have the time to test the trackball itself because I still did not receive the ADSN5050 sensor. The first time I bought it from Ebay, but after 2 months waiting I was just notified that the box was lost :/. I did a 2nd purchase recently from Aliexpress and I hope this time it will arrive (sooner or later), so that I can test everything.
So far I've only be able to verify that the programming of the MCU works, but nothing more.

However the bigger problem for me for such kind of projects is always the mechanical design part, not the SW or electronics. Adding one or more buttons is something easy from the SW/electronics point of view, but I have very little clue on how to modify the case in order to adapt for that. Recently I tried some tutorial for FreeCAD, but I fear I'm still quite far for being able to modify the case properly :/

BTW, I don't know if you already know [this github repo](https://github.com/jfedor2), but it contains several trackball designs very similar to the Ploopy one which integrates also buttons!
Perhaps he already designed something close to what you are looking for ;)

**Comment by sommerper** [comment]
Thanks for the detailed reply! Ok, I'll keep an eye on the project for now and see how it develops.
I'm actually less worried about the case because mostly I end up doing my own design anyway.
And thank you for the link. I had indeed not seen that yet and it also contains some cool trackballs.

**Comment by valeriosetti** [comment]
Ok, if the mechanical design is not a problem for you, the from the firmware point of view I think the design is based in QMK. They have a fork of the main repository [here](https://github.com/ploopyco/qmk-firmware-ploopyco-dev) and inside that one there are `ploopy/*` specific branches such as `ploopyco/mini_fixes`.

I'm really a beginner on QMK and I never tried to build a mouse before. However I added mouse buttons to my ErgoDash keyboard, and it was super easy.

**Comment by valeriosetti** [comment]
PS = in case in the future you want to try to build the ploopy nano yourself, please consider replacing the optical sensor (ADSN5050) with something newer and easier to buy. As I mentioned earlier, I didn't consider this during my development and now I'm stuck in buying that component. Perhaps PMW3360 and similar are much easy to find (also check which one is already supported in QMK if you don't want to write too much code, of course)

**Comment by sommerper** [comment]
Thanks for your suggestion! And sorry for not closing this earlier!
